data:
  root: data/processed_data
  batch_size: 8
  eval_batch_size: 8
  num_workers: 0
  pin_memory: true
  persistent_workers: false
model:
  model_name: vit_base_patch16_224.augreg_in21k
  pretrained: true
  img_size: 224
  drop_rate: 0.1
  drop_path_rate: 0.1
train:
  run_name: vit_base_patch16_224_augreg_in21k_processed_v2
  epochs: 30
  lr: 3.0e-05
  weight_decay: 0.05
  warmup_epochs: 3
  min_lr: 1.0e-06
  label_smoothing: 0.1
  amp: true
  seed: 42
  eval_test: false
augment:
  train_scale:
  - 0.8
  - 1.0
  horizontal_flip_probability: 0.5
  vertical_flip_probability: 0.0
  random_erasing_probability: 0.0
  color_jitter: 0.0
  crop_pct: 0.9
